CREATE OR REPLACE MASKING POLICY "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_MASKING_POLICY_[SAMPLE_DATABASE].[PUBLIC].[SAMPLE_TABLE].[SAMPLE_COLUMN]"
AS (VALUE VARCHAR) RETURNS VARCHAR ->
  case
    when current_role() in ('ANALYST') then "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_FUNCTION_ON_COLUMN_[SAMPLE_DATABASE].[PUBLIC].[SAMPLE_TABLE].[SAMPLE_COLUMN]"(VALUE, CURRENT_STATEMENT(), SESSION_CONTEXT('USER'))
    else VALUE
  end;