ALTER TABLE "SAMPLE_DATABASE"."PUBLIC"."SAMPLE_TABLE"
MODIFY COLUMN "SAMPLE_COLUMN"
SET MASKING POLICY "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_MASKING_POLICY_[SAMPLE_DATABASE].[PUBLIC].[SAMPLE_TABLE].[SAMPLE_COLUMN]";