CREATE DATABASE "SAMPLE_DATABASE" COMMENT = 'v1.0.0.' DATA_RETENTION_TIME_IN_DAYS = 1;
USE DATABASE "SAMPLE_DATABASE";
CREATE SCHEMA "SAMPLE_SCHEMA" COMMENT = 'v1.0.0.';
USE SCHEMA "SAMPLE_SCHEMA";
CREATE TABLE "SAMPLE_DATABASE"."PUBLIC"."SAMPLE_TABLE"
(
    "SAMPLE_COLUMN" VARCHAR(16777216)
);