CREATE OR REPLACE SECURE EXTERNAL FUNCTION "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_FUNCTION_ON_COLUMN_[SAMPLE_DATABASE].[PUBLIC].[SAMPLE_TABLE].[SAMPLE_COLUMN]"
(VALUE VARCHAR, CURRENT_STATEMENT VARCHAR, USER VARCHAR)
RETURNS VARCHAR
NOT NULL
CALLED ON NULL INPUT
IMMUTABLE
REQUEST_TRANSLATOR = "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_REQUEST_TRANSLATOR"
RESPONSE_TRANSLATOR = "SAMPLE_DATABASE"."SAMPLE_SCHEMA"."SAMPLE_RESPONSE_TRANSLATOR"
COMPRESSION = AUTO
MAX_BATCH_ROWS = 1024
API_INTEGRATION = "AWS_API_INTEGRATION_[SAMPLE_DATABASE]"
COMMENT = 'v1.0.0'
HEADERS = (
) CONTEXT_HEADERS = (
   CURRENT_USER
  ,CURRENT_CLIENT
  ,CURRENT_SESSION
  ,CURRENT_TIMESTAMP
  ,CURRENT_DATABASE
  ,CURRENT_SCHEMA
  ,CURRENT_WAREHOUSE
  ,CURRENT_VERSION
  ,CURRENT_ACCOUNT
  ,CURRENT_ROLE
  ,CURRENT_REGION
  ,LAST_QUERY_ID
  ,CURRENT_IP_ADDRESS
) AS '${AWS_API_GATEWAY_URL_OF_API_INTEGRATION}';